export { fetchTMDB, fetchTMDBSafe } from "./client";

export {
  getTrending,
  getPopularMovies,
  getTopRatedMovies,
  getUpcomingMovies,
  getNowPlayingMovies,
  getPopularTV,
  getTopRatedTV,
  getAiringTodayTV,
  getOnTheAirTV,
  discoverByGenre,
  discoverKidsSafe,
  getMovieDetails,
  getTVDetails,
  getTVSeasonDetails,
  multiSearch,
  searchMovies,
  searchTV,
  getMovieGenres,
  getTVGenres,
} from "./endpoints";

export {
  tmdbImage,
  tmdbBackdrop,
  tmdbPoster,
  tmdbProfile,
  getTitle,
  getYear,
  getMediaType,
  getRating,
  formatRuntime,
  formatEpisodeCount,
  selectBestTrailer,
  getTrailerKey,
  getYouTubeEmbedUrl,
  getYouTubeThumbnail,
  getDirectors,
  getWriters,
  getKeyCrewMembers,
  cleanMovie,
  normalizeResults,
  mapToHero,
  buildContentRow,
} from "./mappers";
